site_name: Expy
site_url: https://github.com/ray306/expy
site_description: Psychological experiment scaffold
site_author: Jinbiao Yang

repo_url: https://github.com/ray306/expy

pages:
  - Overview: index.md
  - User Guide:
    - Quickstart: quickstart.md
    - Cookbook: cookbook.md
    - Tips & tricks: tip.md
    - API referrence: api.md
    - Key Mapping: keymap.md
  - About:
    - Changelog: changelog.md

markdown_extensions:
    - toc:
        permalink: True

copyright: Copyright (c) 2016 Jinbiao Yang
