site_name: Expy
site_url: https://github.com/ray306/expy
site_description: Psycho Experiment scaffold
site_author: Jinbiao(Ray) Yang

repo_url: https://github.com/ray306/expy

pages:
  - Overview: index.md
  - User Guide:
    - Quickstart: example.md
    - Cookbook: cookbook.md
    - Functions: functions.md
    - API: api.md
    - Key Mapping: keymap.md
  - About:
    - Changelog: changelog.md


copyright: Copyright (c) 2016 Jinbiao(Ray) Yang
